### ISSUE TITLE
metadata missing?

### ISSUE THREAD

**Issue by ikke-t** [myllynen/rhel-ansible-roles#1]
Did you miss metadata? It seems you use external roles, like aap config, but I don't see where it's listed as dependency.

**Comment by myllynen** [comment]
An Ansible collection must include `galaxy.yml` which is present but `meta` directory is optional, see:

https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_structure.html
https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html
